### ISSUE TITLE
브랜칭 전략 관련 논의

### ISSUE THREAD

**Issue by SeoSang** [dnd-side-project/dnd-6th-10-a-piece-of-writing#12]
커밋 예시
1. feat : 새로운 기능 추가
2. [feat] 새로운 기능 추가
3. feat - 새로운 기능 추가

어떤 커밋 포맷이 좋으신가요?

**Comment by seaworld0125** [comment]
저는 1, 3번이 좋은 것 같습니다

**Comment by carnival77** [comment]
전 2번이 좋은 것 같아요

**Comment by SeoSang** [comment]
저는 2번, 1번 정도가 괜찮은거 같습니다.

다른 프로젝트들은 어떻게 하나 살펴보려고 next js 나 react 레포의 커밋내역을 한번 봤는데 엄청 섞어쓰네요 ㅎㅎ

![image](https://user-images.githubusercontent.com/28820058/149616896-b367c2ac-19a0-49a9-90ac-0ab50540f3d1.png)

**Comment by seaworld0125** [comment]
그렇군요 ㅎㅎ 해솔님 의견 받아서 다수결로 정하면 되겠네요! 

그리고 혹시 커밋 메시지에 이슈 번호도 포함 시키는지 궁금합니다!

**Comment by phaesol** [comment]
저도 2번이 좋은 것 같아요 ! readme 읽어봤는데 저는 그대로 찬성입니당!
