### ISSUE TITLE
이미지 텍스트 추출 방법

### ISSUE THREAD

**Issue by seaworld0125** [dnd-side-project/dnd-6th-10-a-piece-of-writing#22]

**Comment by seaworld0125** [comment]
개인적으로 Google Cloud 에서 제공하는 OCR - 이미지의 텍스트 감지 서비스와 Google cloud storage를 사용하면 좋을 것 같다고 생각합니다. 

OCR - 이미지의 텍스트 감지 서비스
- https://cloud.google.com/vision/docs/ocr#detect_text_in_a_remote_image 

Google cloud storage
- https://cloud.google.com/storage/docs/uploading-objects?hl=ko#uploading-an-object

**간단하게 구상해본 워크플로우입니다.** Cloud storage 대신 AWS S3도 가능하겠지만 S3는 CI/CD 용으로 사용할 계획이어서 공용 Storage로 사용하기에는 적합하지 않다고 생각이 들었습니다.

![image](https://user-images.githubusercontent.com/75168305/150437456-33c0c7dd-bbbc-4574-8e63-a7818f040d75.png)

**텍스트 감지 서비스(vision API) 테스트 결과입니다.**

![image](https://user-images.githubusercontent.com/75168305/150437533-02360bde-07e2-473e-a10e-7cea4dde330a.png)
![image](https://user-images.githubusercontent.com/75168305/150437587-26cfd9c7-785b-499a-a7bd-200dc1c621ec.png)

**직접 촬영한 사진 + cloud storage 업로드 + vision API 테스트 결과입니다**

![image](https://user-images.githubusercontent.com/75168305/150437652-6eca4efa-4ad7-4703-8496-8a5d5832b44c.png)

평균 응답 딜레이 시간은 3~6초입니다.

**Comment by SeoSang** [comment]
@seaworld0125

오호, 잘 읽었습니다.  말씀해주신 방식 너무 좋은 것 같습니다 ! 😄

저는 [tesseract.js](https://tesseract.projectnaptha.com/) 를 로컬에 설치해서 테스트해봤는데요, 잘 동작하긴 합니다.
헌데 tessaract 라이브러리가 무거워서 웹 번들이 불필요하게 무거워지지 않을까 걱정했는데, 
말씀해주신 구글 vision API 를 사용하면 대체할 수 있을 것 같네요 !

만약에 vision API 를 이용하는데 이슈가 생긴다면 그 때 tessaract 를 사용하는 방향으로 가면 될 것 같습니다.
(google cloud platform 에서 저장 후 이미지 url 받아오는 부분까지는 동일하게 가고 vision API 대신 프론트 자체 api 로 tessaract 사용)

테스트하는 김에 구글 클라우드 플랫폼도 한번 가입해서 사용해보려고 합니다. (가격은 3달 무료네용, 이 부분도 저희 웹서비스를 계속 유지해야된다면 어떻게 할건지 생각해봐야겠네요)

**Comment by SeoSang** [comment]
#### tessaract test

![image](https://user-images.githubusercontent.com/28820058/150632496-03cbef41-7727-4b50-b7c3-4fdcc61e9b3e.png)


![image](https://user-images.githubusercontent.com/28820058/150632492-d0d820c6-cf62-4bd3-94c0-43b592dd8fb9.png)

**Comment by seaworld0125** [comment]
@SeoSang 

Tessaract.js 도 좋은 라이브러리 같네요!
말씀하신 대로 vision API는 가격 정책에 대해서 얘기해 볼 필요가 있을 것 같습니다. 😀

**Comment by seaworld0125** [comment]
![image](https://user-images.githubusercontent.com/75168305/150679068-b768c9ba-8247-46a5-a62e-afa237a21efb.png)

최종 워크플로우입니다.
