### ISSUE TITLE
[프론트엔드] 사진 + 텍스트 방식 리서치

### ISSUE THREAD

**Issue by SeoSang** [dnd-side-project/dnd-6th-10-a-piece-of-writing#26]
### 이슈 내용

배경사진을에 입력한 텍스트를 합쳐주는 방식을 어떤 식으로 구현할지 리서치, 결정이 필요하다.

**Comment by SeoSang** [comment]
### 워터마크 처리

우리 서비스에 맞는 매우 좋은 라이브러리가 있네요

https://brianium.github.io/watermarkjs/

- 이미지 위에 이미지 형태로 입혀주는 기능
- 이미지 위에 텍스트 형태로 입혀주는 기능
  - 텍스트 크기, 폰트, 색상, 투명도 전무 조절 가능
- 적용 위치 조절 가능
- 이미지 투명도 설정 가능

**Comment by SeoSang** [comment]
## 배경사진을 바탕으로한 게시글 작성 

배경사진을 바탕으로한 게시글 작성  개발적으로 어떻게 구현할지 여러 방식 고안중


### 1. 이미지 editor 를 이용

- Toast ui image editor 이용해서 이미지 형태로 저장 및 로드
- http://nhn.github.io/tui.image-editor/latest/tutorial-example01-includeUi

#### 유저 게시글 업로드  flow

1. 유저가 배경이미지를 업로드
2. 이미지 editor 로 이미지 수정
3. 업로드 버튼 클릭
4. ~~프론트에서 이미지 워터마크 처리~~ (내보내기 시에 워터마크 처리하는 것이 더 좋아보이네요)
5. ~~워터마크 처리 된 이미지~~ API로 백엔드로 전송
6. 백엔드에서 cloud 에 이미지 저장
7. db에는 이미지 url 단위로 보관


#### 저장된 게시글을 확인하는 flow

1. 유저가 피드 열람
2. 프론트에서 백엔드로 load API 전송
3. 백엔드 db image url을 받음
4. 이미지 형태로 유저에게 보여짐 (한번 저장하면 텍스트 수정 불가)

#### 내보내기 flow

1. 유저가 내보내기 버튼 클릭
2. 프론트에서 이미지 바탕으로 워터마크 처리
3. 워터마크 처리된 이미지 `png` or `jpg` 형태로 저장

장점

- 이미지 크기 제한을 할 필요가 없음
- 유저가 조금 더 디테일하게 커스텀 가능
  - 에디터에서 많은 기능을 제공
- 스펙 관련 결정사항이 많이 줄어들음
- 개발적으로 side effect 가 가장 적을 것 같은 방향

단점

- 한번 저장되면 이미지 텍스트 수정 불가
- 제공되는 에디터가 모바일에서 조금 불편할 수가 있음


### 2. 이미지 + 텍스트로 직접 만들어주기

- 이미지와 텍스트를 개별적으로 적용하는 방식

#### 유저 게시글 업로드 flow

1. 유저가 배경이미지 업로드
2. 정해진 사이즈로 이미지 크롭 유도
3. API 로 배경 이미지 저장 
4. 유저가 그 위에 들어갈 텍스트는 따로 작성 (여기서 텍스트를 어떻게 제한할지 구체화 필요)
5. 업로드 버튼 클릭
6. db에는 이미지 따로, 내부 텍스트 따로 저장 


아래처럼 이미지를 몇가지 크기로 제한 (제한하지 않으면 이미지 위에 텍스트를 어떻게 그릴지 구체화하기가 어렵다)

- 4 : 3 세로
- 4 : 3 가로
- 정방형
- [crop 에 사용될 라이브러리](https://fengyuanchen.github.io/cropperjs/) 

#### 저장된 게시글을 확인하는 flow

1. 유저가 피드 열람
2. 프론트에서 백엔드로 load API 전송
3. 백엔드 db 에서 image url 과 텍스트 모두 로드
4. 로드한 이미지 결과를 background로 하는 div에 텍스트를 담아 보여줌 (css 스타일링 필요)

(텍스트를 이미지 위에 어떻게 보여질지 구체화가 반드시 필요)

#### 내보내기 flow

1. 유저가 내보내기 버튼 클릭
2. 라이브러리를 이용해서 게시글 div 엘리먼트를 캡쳐
3. 프론트에서 워터마크 처리
4. 워터마크 처리된 이미지 `png` or `jpg` 형태로 저장


장점

- 텍스트 형태도 저장되기 때문에 본문 검색 가능
- 유저 입장에서는 텍스트만 작성해도 알아서 이쁘게 정렬해주는? 경험을 할 수 있음

단점

- 유저가 직접 디자인을 커스텀하기가 어려움
- 텍스트의 양, 크기 등 제약조건이 많이 필요함
- 텍스트를 사진 어디에 위치시킬 것인지
- db에 텍스트를 저장하는 방식에 대한 협의가 필요함

**Comment by seaworld0125** [comment]
백엔드는 이미지를 저장하는 api를 우선적으로 구현하겠습니다

**Comment by papillon28** [comment]
디자인 피드백 시간에 받았던 피드백 중 하나가, '유사 서비스를 기획해 본 경험이 있는데 보통 다들 데이터베이스가 많이 쌓이면 분류하고 찾는게 어려워서 더이상 저장해놓은 것을 보지 않게 된다'고 들어서요, 그래서 저는 본문 내용이 검색 가능한 후자가 좋아 보이네요

근데 후자는 디자인 커스텀이 어디까지 가능하고 어디부터는 어려운걸까요?? 그 범위가 감이 잘 안잡힙니다
* 이미지는 무조건 1:1 비율
* 글자 크기는 대, 중, 소
* 텍스트 정렬 왼쪽정렬, 중앙, 오른쪽
* 폰트 변경 (5가지정도)
*글자 색 어두운색, 흰색
이 중에서 어려운 기능이 있을까요??

**Comment by SeoSang** [comment]
@papillon28 

말씀해주신 부분은 아마 대부분 가능할 것 같은데요,

다만 디바이스 크기에 따라 텍스트 줄바꿈이 달라질 수 있어서 유저가 처음에 작성했던 구도랑 나중에 다른 환경에서 열었을 떄랑 디자인이 다르게 보여지는 케이스가 있을 수 있고,
텍스트를 이미지 크기에 맞게 제한을 둬야하는데 이것 또한 화면 크기에 따라 달라질 수 있기에
배경이미지 바탕으로 된 포스트를 고정 width에 고정 height으로 가야될 것 같은데 괜찮을까요?

**Comment by papillon28** [comment]
@SeoSang 마지막 부분이.. 잘 이해되지 않습니다! 머리에 그려지지 않네요
아니면은 저장 자체는 텍스트 + 이미지로 하되 서비스에 올라가 홈피드같은데에서 겉으로 보일때는 합쳐진 이미지인건 어려울까요??

**Comment by SeoSang** [comment]
네네 제가 말씀드린 2안이 그 방식이었습니다!
저희가 모바일과 웹을 둘다 고려하다보니, 이미지(포스트를 이미지라고 칭할게요)  크기가 달라질 수 있잖아요?
화면이 바뀔때마다 고려해야하는 것들이 많게 되기 때문에 2안으로 가면 그 크기를 고정해야 할 수도 있다는 말씀이었어요.
물론 하나하나 케이스를 고려해가면서 저희가 스펙을 정의하면 가변으로 할수도 있긴 하겠지만.... 
미팅때 더 자세히 얘기해보는게 좋겠네요 !

@papillon28

**Comment by SeoSang** [comment]
@papillon28

아영님 관련해서 오늘 회의 때 논의 했는데요,
1안으로 가되 입력받은 텍스트를 추가적으로 저장해서 검색이 가능하도록 하는 방향으로 생각중입니다.


- [Toast UI Editor](http://nhn.github.io/tui.image-editor/latest/tutorial-example01-includeUi) 를 이용해 이미지 형태로 저장
- image edit 할 때 입력된 텍스트 추가 저장 (텍스트가 저장됐기 때문에 검색이 가능)
- 로드할 때 이미지 형태로 로드

이렇게 구현해보려하는데 이미지 에디터에서 텍스트 기능을 제공할지가 확실치가 않아서 혹시 확인해보고 말씀드리겠습니다 !

**Comment by papillon28** [comment]
@SeoSang 확인했습니다! 저는 무슨 방향이든 텍스트를 검색할수만 있으면 되기에 이미지 비율이나 형태는 어떻게 되든 괜찮을 것 같아요, 핀터레스트와 유사한 Masonry 스타일/ 혹은 임의로 이미지를 잘라내서 1:1로 가는 방향 둘 중 하나로 정해지는 것으로 생각하고 있겠습니다

만약 텍스트 저장이 안된다면.. 그러면 태그를 좀더 자세하게 분화해놓는게 방법일 것 같아요! 모로 가도 검색만 편하면 됩니다
