### ISSUE TITLE
[디자인 & 프론트] 메인 화면

### ISSUE THREAD

**Issue by SeoSang** [dnd-side-project/dnd-6th-10-a-piece-of-writing#31]
### 주요 내용

메인 화면 구성 관련 이슈

**Comment by SeoSang** [comment]
### 메인화면 적용 예시

![image](https://user-images.githubusercontent.com/28820058/151398701-0578ada4-890a-4845-9212-35c921f8d2fd.png)

**Comment by papillon28** [comment]
상혁님 핀터레스트 스타일 확정인가요?!

**Comment by SeoSang** [comment]
아니용, 업로드 이미지 비율을 1대1로 고정시키지 않는다면 자유도가 생기면 아래 화면이 불가능할 것 같아 가능할지 테스트삼아 구현해보았습니다~

![image](https://user-images.githubusercontent.com/28820058/152350266-3118adbc-10c7-49c8-b4dd-1f664811369b.png)

@papillon28
