### ISSUE TITLE
[공통] 논의할 사항들 모음

### ISSUE THREAD

**Issue by SeoSang** [dnd-side-project/dnd-6th-10-a-piece-of-writing#36]
### 주요 내용

논의할것들

- [X] 글씨 색 부분 svg 화이트버전 필요함
![Pasted Graphic](https://user-images.githubusercontent.com/28820058/153040646-8af2cd88-c06e-48a6-904c-8055a8528257.png)

- [X] 이미지 업로드 부분 논의
- [x] 글자가 길어져서 이미지를 넘치면 어떻게 할지?
- [x] 원본 출처도 글씨체, 글씨 크기 따라가도록 할 것인지 (글씨 색도 어떻게할건지)
- [x] 태그 선택됐을 때 색깔 변경이 필요하지 않을지? (현재는 체크 아이콘만 추가)

기타 생기게 되면 이 이슈에 기록하겠습니다.

**Comment by papillon28** [comment]
혹시 svg fill 옵션 어떻게 되었나요??

**Comment by SeoSang** [comment]
- [x] 이미지 업로드 버튼이 맨 왼쪽이 낫지 않을까 -> 왼쪽으로 놓는걸로 수정
- [ ] 태그 검색 후 로직 어떻게 될 것인지
- [ ] 완료 안내 창들은 그냥 브라우저 기본 기능 쓰면 될지
- [ ] 태그 선택 시 bg 색상
